// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'package:ridesync/core/firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJiHuDmwCJEOCt2s2qMDTi1szrB-XQJ9c',
    appId: '1:559580096397:web:dd2afa3eb793ce3793ffc4',
    messagingSenderId: '559580096397',
    projectId: 'ridesync-2003',
    authDomain: 'ridesync-2003.firebaseapp.com',
    storageBucket: 'ridesync-2003.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjP2DeDeLBg9OdYj5CA9F2C0dhiskVPsk',
    appId: '1:559580096397:android:d0798a0111cab5c893ffc4',
    messagingSenderId: '559580096397',
    projectId: 'ridesync-2003',
    storageBucket: 'ridesync-2003.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7zjtpH4pj_cDQIGN52g4bT2JRx7-iwdg',
    appId: '1:559580096397:ios:55b0ba963620c50293ffc4',
    messagingSenderId: '559580096397',
    projectId: 'ridesync-2003',
    storageBucket: 'ridesync-2003.firebasestorage.app',
    iosBundleId: 'com.ridesync.ridesync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7zjtpH4pj_cDQIGN52g4bT2JRx7-iwdg',
    appId: '1:559580096397:ios:55b0ba963620c50293ffc4',
    messagingSenderId: '559580096397',
    projectId: 'ridesync-2003',
    storageBucket: 'ridesync-2003.firebasestorage.app',
    iosBundleId: 'com.ridesync.ridesync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJiHuDmwCJEOCt2s2qMDTi1szrB-XQJ9c',
    appId: '1:559580096397:web:6c6e659b55cab42b93ffc4',
    messagingSenderId: '559580096397',
    projectId: 'ridesync-2003',
    authDomain: 'ridesync-2003.firebaseapp.com',
    storageBucket: 'ridesync-2003.firebasestorage.app',
  );
}




